# Generated by Django 5.2 on 2025-04-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='reading',
            name='notes',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateField(verbose_name='Current Reading Date'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='status',
            field=models.CharField(choices=[('S', 'Started'), ('P', 'In Progress'), ('F', 'Finished'), ('R', 'Re-read')], default='S', max_length=1),
        ),
    ]
